export const defaultData = {
  Kitchen: [
    {
      name: 'Electric Stovetop',
      quantity: 0,
      watts: 1000,
      hours: 0.5,
      total: 0,
      icon: 'KitchenStoveTop',
    },
    {
      name: 'Electric Oven',
      quantity: 0,
      watts: 4000,
      hours: 0.5,
      total: 0,
      icon: 'KitchenOven',
    },
    {
      name: 'Kettle',
      quantity: 0,
      watts: 2000,
      hours: 0.1,
      total: 0,
      icon: 'KitchenKettle',
    },
    {
      name: 'Toaster',
      quantity: 0,
      watts: 1500,
      hours: 0.1,
      total: 0,
      icon: 'KitchenToaster',
    },
    {
      name: 'Fridge - Large',
      quantity: 0,
      watts: 200,
      hours: 4,
      total: 0,
      icon: 'KitchenLargeFridge',
    },
    {
      name: 'Bar Fridge',
      quantity: 0,
      watts: 65,
      hours: 4,
      total: 0,
      icon: 'KitchenSmallFridge',
    },
    {
      name: 'Freezer',
      quantity: 0,
      watts: 250,
      hours: 8,
      total: 0,
      icon: 'KitchenFreezer',
    },
    {
      name: 'Microwave',
      quantity: 0,
      watts: 600,
      hours: 0.1,
      total: 0,
      icon: 'KitchenMicrowave',
    },
    {
      name: 'Dishwasher',
      quantity: 0,
      watts: 500,
      hours: 1,
      total: 0,
      icon: 'KitchenDishwasher',
    },
    {
      name: 'Coffee Machine',
      quantity: 0,
      watts: 1200,
      hours: 0.2,
      total: 0,
      icon: 'KitchenCoffeeMachine',
    },
    {
      name: 'Rangehood',
      quantity: 0,
      watts: 150,
      hours: 1,
      total: 0,
      icon: 'KitchenRangehood',
    },
    {
      name: 'Air Fryer',
      quantity: 0,
      watts: 2000,
      hours: 0.5,
      total: 0,
      icon: 'KitchenAirFryer',
    },
  ],
  Laundry: [
    {
      name: 'Dryer',
      quantity: 0,
      watts: 500,
      hours: 1,
      total: 0,
      icon: 'BathLaundryClothesDryer',
    },
    {
      name: 'Washing Machine',
      quantity: 0,
      watts: 500,
      hours: 1,
      total: 0,
      icon: 'BathLaundryWashingMachine',
    },
    {
      name: 'Iron',
      quantity: 0,
      watts: 110,
      hours: 0.2,
      total: 0,
      icon: 'BathLaundryIron',
    },
  ],
  Bathroom: [
    {
      name: 'Hair Dryer',
      quantity: 0,
      watts: 1000,
      hours: 0.1,
      total: 0,
      icon: 'BathLaundryHairdryer',
    },
    {
      name: 'Electric Towel Rail',
      quantity: 0,
      watts: 1000,
      hours: 0.5,
      total: 0,
      icon: 'BathLaundryHeatedTowelRail',
    },
    {
      name: 'Radiator/Heater',
      quantity: 0,
      watts: 2000,
      hours: 0.5,
      total: 0,
      icon: 'BathLaundryRadiator',
    },
  ],
  Entertainment: [
    {
      name: 'TV',
      quantity: 0,
      watts: 200,
      hours: 6,
      total: 0,
      icon: 'OfficeTv',
    },
    {
      name: 'Computers',
      quantity: 0,
      watts: 70,
      hours: 2,
      total: 0,
      icon: 'OfficeComputer',
    },
    {
      name: 'Internet/Modem',
      quantity: 0,
      watts: 20,
      hours: 4,
      total: 0,
      icon: 'OfficeModem',
    },
    {
      name: 'Gaming Console',
      quantity: 0,
      watts: 200,
      hours: 2,
      total: 0,
      icon: 'OfficeGamingConsole',
    },
  ],

  Household: [
    {
      name: 'Lights',
      quantity: 0,
      watts: 40,
      hours: 8,
      total: 0,
      icon: 'HouseholdLights',
    },
    {
      name: 'Outdoor Floodlights - Large',
      quantity: 0,
      watts: 300,
      hours: 2,
      total: 0,
      icon: 'UtilityOutdoorLighting',
    },
    {
      name: 'Slab Heating',
      quantity: 0,
      watts: 200,
      hours: 4,
      total: 0,
      icon: 'UtilitySlabHeating',
    },
    {
      name: 'Bar/Oil Heater',
      quantity: 0,
      watts: 2400,
      hours: 2,
      total: 0,
      icon: 'HouseholdBarOilHeater',
    },
    {
      name: 'Ceiling Fan',
      quantity: 0,
      watts: 75,
      hours: 2,
      total: 0,
      icon: 'HouseholdCeilingFan',
    },
  ],
  Utilities: [
    {
      name: 'Electric Hot Water',
      quantity: 0,
      watts: 3000,
      hours: 3,
      total: 0,
      icon: 'UtilityHotWaterService',
    },
    {
      name: 'Air Conditioning - Reverse Cycle',
      quantity: 0,
      watts: 4000,
      hours: 3,
      total: 0,
      icon: 'HouseholdAirCon',
    },
    {
      name: 'Vacuum Cleaner',
      quantity: 0,
      watts: 800,
      hours: 1,
      total: 0,
      icon: 'HouseholdVaccumm',
    },
    {
      name: 'Pool Heating',
      quantity: 0,
      watts: 300,
      hours: 12,
      total: 0,
      icon: 'UtilitySwimmingPool',
    },
    {
      name: 'Pool Pump',
      quantity: 0,
      watts: 2500,
      hours: 6,
      total: 0,
      icon: 'UtilityPump',
    },
    {
      name: 'Septic Pump',
      quantity: 0,
      watts: 700,
      hours: 1,
      total: 0,
      icon: 'UtilityPump',
    },
    {
      name: 'Water Pump',
      quantity: 0,
      watts: 150,
      hours: 4,
      total: 0,
      icon: 'OutdoorPondPump',
    },
  ],
  Workshop: [
    {
      name: 'Compressor',
      quantity: 0,
      watts: 1600,
      hours: 1,
      total: 0,
      icon: 'WorkshopCompressor',
    },
    {
      name: 'Drill Press',
      quantity: 0,
      watts: 500,
      hours: 0.2,
      total: 0,
      icon: 'WorkshopDrillPress',
    },
    {
      name: 'Welder - Small',
      quantity: 0,
      watts: 3000,
      hours: 0.2,
      total: 0,
      icon: 'WorkshopWelder',
    },
    {
      name: 'Battery Charger',
      quantity: 0,
      watts: 150,
      hours: 12,
      total: 0,
      icon: 'WorkshopBatteryCharger',
    },
    {
      name: 'Saw Bench',
      quantity: 0,
      watts: 1400,
      hours: 0.2,
      total: 0,
      icon: 'WorkshopBenchSaw',
    },
  ],
  Outdoor: [
    {
      name: 'Pond Pump',
      quantity: 0,
      watts: 50,
      hours: 24,
      total: 0,
      icon: 'OutdoorPondPump',
    },
    {
      name: 'Patio Heater',
      quantity: 0,
      watts: 2800,
      hours: 2,
      total: 0,
      icon: 'OutdoorPatioHeaterFreestanding',
    },
    {
      name: 'Tennis Court Lights',
      quantity: 0,
      watts: 200,
      hours: 4,
      total: 0,
      icon: 'OutdoorTennisCourtLight',
    },
    {
      name: 'Electric Chainsaw',
      quantity: 0,
      watts: 1200,
      hours: 1,
      total: 0,
      icon: 'OutdoorChainsaw',
    },
  ],
}
